SELECT 
  B.NAME AS DEPARTMENT,
  A.NAME AS EMPLOYEE,
  A.SALARY
FROM 
  (
  SELECT 
    NAME,
    SALARY,
    DEPARTMENTID,
    DENSE_RANK() OVER (PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) AS RNK
  FROM EMPLOYEE
) A LEFT OUTER JOIN 
DEPARTMENT B
ON B.ID = A.DEPARTMENTID
WHERE A.RNK <= 3
